services:
  ai-chat-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_BASE_URL=http://192.168.0.223:11434
      - OLLAMA_MODEL=llama3.2
    volumes:
      - .:/app
    restart: unless-stopped
    network_mode: host

networks:
  ai-chat-network:
    driver: bridge 