version: '3.8'

services:
  ai-chat-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - OLLAMA_MODEL=llama3.2
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - ai-chat-network

networks:
  ai-chat-network:
    driver: bridge 